-- ============================================================
-- Report: ADM20001__Configuration Comparison Report (System).rpt
Path:   ADM20001__Configuration Comparison Report (System).rpt
Extracted: 2026-05-07 18:02:38
-- Source: Subreport [Chart of Accounts ]
-- Table:  Command
-- ============================================================

SELECT 1 AS "Type", T1."AcctCode" AS "AcctCode_1", IFNULL(T2."AcctCode", T1."AcctCode") AS "AcctCode_2", T1."AcctName" AS "AcctName_1", IFNULL(T2."AcctName", T1."AcctName") AS "AcctName_2", T1."Postable" AS "Postable_1", T2."Postable" AS "Postable_2", T1."Levels" AS "Levels_1", IFNULL(T2."Levels", T1."Levels") AS "Levels_2", T1."ExportCode" AS "ExportCode_1", T2."ExportCode" AS "ExportCode_2", T1."GrpLine" AS "GrpLine_1", IFNULL(T2."GrpLine", T1."GrpLine") AS "GrpLine_2", T1."GroupMask" AS "GroupMask_1", IFNULL(T2."GroupMask", T1."GroupMask") AS "GroupMask_2", T1."RateTrans" AS "RateTrans_1", T2."RateTrans" AS "RateTrans_2", T1."FrgnName" AS "FrgnName_1", T2."FrgnName" AS "FrgnName_2", T1."Details" AS "Details_1", T2."Details" AS "Details_2", T1."Project" AS "Project_1", T2."Project" AS "Project_2", T1."FormatCode" AS "FormatCode_1", IFNULL(T2."FormatCode", T1."FormatCode") AS "FormatCode_2", T1."ExchRate" AS "ExchRate_1", T2."ExchRate" AS "ExchRate_2", T1."DfltVat" AS "DfltVat_1", T2."DfltVat" AS "DfltVat_2", T1."VatChange" AS "VatChange_1", T2."VatChange" AS "VatChange_2", T1."TransCode" AS "TransCode_1", T2."TransCode" AS "TransCode_2", T1."DfltTax" AS "DfltTax_1", T2."DfltTax" AS "DfltTax_2", T1."TaxPostAcc" AS "TaxPostAcc_1", T2."TaxPostAcc" AS "TaxPostAcc_2", T1."PlngLevel" AS "PlngLevel_1", T2."PlngLevel" AS "PlngLevel_2", T1."SnapShotId" AS "SnapShotId_1", T2."SnapShotId" AS "SnapShotId_2", T1."Budget" AS "Budget_1", T2."Budget" AS "Budget_2", T1."DoBudget" AS "DoBudget_1", T2."DoBudget" AS "DoBudget_2" 
FROM (SELECT "AcctCode", "AcctName", "Postable", "Levels", "ExportCode", "GrpLine", "GroupMask", "RateTrans", "FrgnName", "Details", "Project", "FormatCode", "ExchRate", "DfltVat", "VatChange", "TransCode", "DfltTax", "TaxPostAcc", "PlngLevel", AACT."SnapShotId", "Budget", "DoBudget" FROM AACT, AADM WHERE AACT."SnapShotId"={?SnapShotId1} AND AADM."SnapShotId"={?SnapShotId1}) T1
FULL JOIN (SELECT "AcctCode", "AcctName", "Postable", "Levels", "ExportCode", "GrpLine", "GroupMask", "RateTrans", "FrgnName", "Details", "Project", "FormatCode", "ExchRate", "DfltVat", "VatChange", "TransCode", "DfltTax", "TaxPostAcc", "PlngLevel", OACT."SnapShotId", "Budget", "DoBudget" FROM OACT, OADM) T2 
ON T1."AcctCode" = T2."AcctCode" 
UNION
SELECT 2 AS "Type", T1."AcctCode" AS "AcctCode_1", IFNULL(T2."AcctCode", T1."AcctCode") AS "AcctCode_2", T1."AcctName" AS "AcctName_1", IFNULL(T2."AcctName", T1."AcctName") AS "AcctName_2", T1."Postable" AS "Postable_1", T2."Postable" AS "Postable_2", T1."Levels" AS "Levels_1", IFNULL(T2."Levels", T1."Levels") AS "Levels_2", T1."ExportCode" AS "ExportCode_1", T2."ExportCode" AS "ExportCode_2", T1."GrpLine" AS "GrpLine_1", IFNULL(T2."GrpLine", T1."GrpLine") AS "GrpLine_2", T1."GroupMask" AS "GroupMask_1", IFNULL(T2."GroupMask", T1."GroupMask") AS "GroupMask_2", T1."RateTrans" AS "RateTrans_1", T2."RateTrans" AS "RateTrans_2", T1."FrgnName" AS "FrgnName_1", T2."FrgnName" AS "FrgnName_2", T1."Details" AS "Details_1", T2."Details" AS "Details_2", T1."Project" AS "Project_1", T2."Project" AS "Project_2", T1."FormatCode" AS "FormatCode_1", IFNULL(T2."FormatCode", T1."FormatCode") AS "FormatCode_2", T1."ExchRate" AS "ExchRate_1", T2."ExchRate" AS "ExchRate_2", T1."DfltVat" AS "DfltVat_1", T2."DfltVat" AS "DfltVat_2", T1."VatChange" AS "VatChange_1", T2."VatChange" AS "VatChange_2", T1."TransCode" AS "TransCode_1", T2."TransCode" AS "TransCode_2", T1."DfltTax" AS "DfltTax_1", T2."DfltTax" AS "DfltTax_2", T1."TaxPostAcc" AS "TaxPostAcc_1", T2."TaxPostAcc" AS "TaxPostAcc_2", T1."PlngLevel" AS "PlngLevel_1", T2."PlngLevel" AS "PlngLevel_2", T1."SnapShotId" AS "SnapShotId_1", T2."SnapShotId" AS "SnapShotId_2", T1."Budget" AS "Budget_1", T2."Budget" AS "Budget_2", T1."DoBudget" AS "DoBudget_1", T2."DoBudget" AS "DoBudget_2" 
FROM (SELECT "AcctCode", "AcctName", "Postable", "Levels", "ExportCode", "GrpLine", "GroupMask", "RateTrans", "FrgnName", "Details", "Project", "FormatCode", "ExchRate", "DfltVat", "VatChange", "TransCode", "DfltTax", "TaxPostAcc", "PlngLevel", AACT."SnapShotId", "Budget", "DoBudget" FROM AACT, AADM WHERE AACT."SnapShotId"={?SnapShotId1} AND AADM."SnapShotId"={?SnapShotId1}) T1
FULL JOIN (SELECT "AcctCode", "AcctName", "Postable", "Levels", "ExportCode", "GrpLine", "GroupMask", "RateTrans", "FrgnName", "Details", "Project", "FormatCode", "ExchRate", "DfltVat", "VatChange", "TransCode", "DfltTax", "TaxPostAcc", "PlngLevel", OACT."SnapShotId", "Budget", "DoBudget" FROM OACT, OADM) T2 
ON T1."AcctCode" = T2."AcctCode"
